"""Initial migration

Revision ID: 3b184f357999
Revises:
Create Date: 2025-12-29 21:34:22.331611

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b184f357999"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("power", sa.Float(), nullable=False),
        sa.Column("ambient_temperature", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_index(
        op.f("ix_data_timestamp"), "data", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_timestamp"), table_name="data")
    op.drop_table("data")
    # ### end Alembic commands ###
